//! Hyprland backend (B3).
//!
//! Hyprland exposes `decoration:screen_shader`, a GLSL fragment shader applied
//! to the final composited output - the same VAC-safe category as the KWin
//! effect (post-game, in the compositor). We bake the saturation into that
//! shader and set it with `hyprctl`. Clearing it removes the pass entirely, so
//! "off" is zero cost.
//!
//! Hyprland screen shaders can't take live uniforms, so each apply rewrites the
//! shader file with the value baked in - cheap, and only happens on change.
//!
//! Untested here (no Hyprland session on the dev box); gated to Hyprland by
//! `detect()` and written against Hyprland's documented shader interface.

use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

use satur8_core::{
    Backend, BackendError, CostNote, Desktop, Environment, Output, Saturation,
};

/// Hyprland screen-shader interface: `tex` sampler, `v_texcoord` varying,
/// `gl_FragColor` output. `{SATURATION}` is baked per apply.
const SCREEN_SHADER_TEMPLATE: &str = r#"// Generated by satur8.
#version 300 es
precision highp float;
in vec2 v_texcoord;
out vec4 fragColor;
uniform sampler2D tex;

void main() {
    vec4 color = texture(tex, v_texcoord);
    float luma = dot(color.rgb, vec3(0.2126, 0.7152, 0.0722));
    vec3 rgb = mix(vec3(luma), color.rgb, float({SATURATION}));
    fragColor = vec4(clamp(rgb, 0.0, 1.0), color.a);
}
"#;

pub struct HyprlandBackend {
    shader_path: PathBuf,
}

impl HyprlandBackend {
    pub fn detect() -> Option<HyprlandBackend> {
        if Environment::detect().desktop != Desktop::Hyprland {
            return None;
        }
        if which("hyprctl").is_none() {
            return None;
        }
        Some(HyprlandBackend {
            shader_path: shader_path()?,
        })
    }

    fn write_shader(&self, saturation: Saturation) -> Result<(), BackendError> {
        if let Some(dir) = self.shader_path.parent() {
            std::fs::create_dir_all(dir)
                .map_err(|e| BackendError::Apply(format!("creating {}: {e}", dir.display())))?;
        }
        let src = SCREEN_SHADER_TEMPLATE
            .replace("{SATURATION}", &format!("{:.4}", saturation.get()));
        let mut f = std::fs::File::create(&self.shader_path)
            .map_err(|e| BackendError::Apply(format!("writing shader: {e}")))?;
        f.write_all(src.as_bytes())
            .map_err(|e| BackendError::Apply(format!("writing shader: {e}")))?;
        Ok(())
    }

    fn hyprctl_screen_shader(&self, value: &str) -> Result<(), BackendError> {
        let out = Command::new("hyprctl")
            .args(["keyword", "decoration:screen_shader", value])
            .output()
            .map_err(|e| BackendError::Apply(format!("running hyprctl: {e}")))?;
        if !out.status.success() {
            return Err(BackendError::Apply(format!(
                "hyprctl failed: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            )));
        }
        Ok(())
    }
}

impl Backend for HyprlandBackend {
    fn name(&self) -> &'static str {
        "hyprland"
    }

    fn cost(&self) -> CostNote {
        CostNote::CompositorShaderPass
    }

    fn outputs(&self) -> Vec<Output> {
        vec![Output {
            id: "all".into(),
            human_name: "All outputs".into(),
        }]
    }

    fn apply(&mut self, _output: &Output, saturation: Saturation) -> Result<(), BackendError> {
        if saturation.is_identity() {
            return self.reset(_output);
        }
        self.write_shader(saturation)?;
        self.hyprctl_screen_shader(&self.shader_path.to_string_lossy())
    }

    fn reset(&mut self, _output: &Output) -> Result<(), BackendError> {
        // Hyprland's sentinel for "no shader".
        self.hyprctl_screen_shader("[[EMPTY]]")
    }
}

fn shader_path() -> Option<PathBuf> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))?;
    Some(base.join("satur8").join("hyprland-satur8.frag"))
}

fn which(bin: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|d| d.join(bin))
        .find(|p| p.is_file())
}
