//! Hyprland backend (B3).
//!
//! Hyprland exposes `decoration:screen_shader`, a GLSL fragment shader applied
//! to the final composited output - the same VAC-safe category as the KWin
//! effect (post-game, in the compositor). We bake the saturation into that
//! shader and set it with `hyprctl`. Clearing it removes the pass entirely, so
//! "off" is zero cost.
//!
//! Hyprland screen shaders can't take live uniforms, so each apply rewrites the
//! shader file with the value baked in - cheap, and only happens on change.
//!
//! Untested here (no Hyprland session on the dev box); gated to Hyprland by
//! `detect()` and written against Hyprland's documented shader interface.

use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

use satur8_core::{Backend, BackendError, CostNote, Desktop, Environment, Output, Saturation};

/// Hyprland screen-shader interface: `tex` sampler, `v_texcoord` varying,
/// `fragColor` output. `{SATURATION}` is baked per apply.
const GAMMA_SCREEN_SHADER_TEMPLATE: &str = r#"// Generated by satur8.
#version 300 es
precision highp float;
in vec2 v_texcoord;
out vec4 fragColor;
uniform sampler2D tex;

void main() {
    vec4 color = texture(tex, v_texcoord);
    float luma = dot(color.rgb, vec3(0.2126, 0.7152, 0.0722));
    vec3 rgb = mix(vec3(luma), color.rgb, float({SATURATION}));
    fragColor = vec4(clamp(rgb, 0.0, 1.0), color.a);
}
"#;

const LINEAR_SCREEN_SHADER_TEMPLATE: &str = r#"// Generated by satur8.
#version 300 es
precision highp float;
in vec2 v_texcoord;
out vec4 fragColor;
uniform sampler2D tex;

float srgb_to_linear_channel(float c) {
    return c <= 0.04045 ? c / 12.92 : pow((c + 0.055) / 1.055, 2.4);
}

vec3 srgb_to_linear(vec3 c) {
    return vec3(
        srgb_to_linear_channel(c.r),
        srgb_to_linear_channel(c.g),
        srgb_to_linear_channel(c.b)
    );
}

float linear_to_srgb_channel(float c) {
    return c <= 0.0031308 ? c * 12.92 : 1.055 * pow(c, 1.0 / 2.4) - 0.055;
}

vec3 linear_to_srgb(vec3 c) {
    return vec3(
        linear_to_srgb_channel(c.r),
        linear_to_srgb_channel(c.g),
        linear_to_srgb_channel(c.b)
    );
}

void main() {
    vec4 color = texture(tex, v_texcoord);
    vec3 linear_rgb = srgb_to_linear(color.rgb);
    float luma = dot(linear_rgb, vec3(0.2126, 0.7152, 0.0722));
    linear_rgb = clamp(mix(vec3(luma), linear_rgb, float({SATURATION})), 0.0, 1.0);
    vec3 rgb = linear_to_srgb(linear_rgb);
    fragColor = vec4(clamp(rgb, 0.0, 1.0), color.a);
}
"#;

pub struct HyprlandBackend {
    shader_path: PathBuf,
    linear_light: bool,
}

impl HyprlandBackend {
    pub fn detect() -> Option<HyprlandBackend> {
        if Environment::detect().desktop != Desktop::Hyprland {
            return None;
        }
        which("hyprctl")?;
        Some(HyprlandBackend {
            shader_path: shader_path()?,
            linear_light: false,
        })
    }

    fn shader_source(&self, saturation: Saturation) -> String {
        shader_source(saturation, self.linear_light)
    }

    fn write_shader(&self, saturation: Saturation) -> Result<(), BackendError> {
        if let Some(dir) = self.shader_path.parent() {
            std::fs::create_dir_all(dir)
                .map_err(|e| BackendError::Apply(format!("creating {}: {e}", dir.display())))?;
        }
        let src = self.shader_source(saturation);
        let mut f = std::fs::File::create(&self.shader_path)
            .map_err(|e| BackendError::Apply(format!("writing shader: {e}")))?;
        f.write_all(src.as_bytes())
            .map_err(|e| BackendError::Apply(format!("writing shader: {e}")))?;
        Ok(())
    }

    fn hyprctl_screen_shader(&self, value: &str) -> Result<(), BackendError> {
        let out = Command::new("hyprctl")
            .args(["keyword", "decoration:screen_shader", value])
            .output()
            .map_err(|e| BackendError::Apply(format!("running hyprctl: {e}")))?;
        if !out.status.success() {
            return Err(BackendError::Apply(format!(
                "hyprctl failed: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            )));
        }
        Ok(())
    }
}

impl Backend for HyprlandBackend {
    fn name(&self) -> &'static str {
        "hyprland"
    }

    fn cost(&self) -> CostNote {
        CostNote::CompositorShaderPass
    }

    fn outputs(&self) -> Vec<Output> {
        vec![Output {
            id: "all".into(),
            human_name: "All outputs".into(),
        }]
    }

    fn apply(&mut self, _output: &Output, saturation: Saturation) -> Result<(), BackendError> {
        if saturation.is_identity() {
            return self.reset(_output);
        }
        self.write_shader(saturation)?;
        self.hyprctl_screen_shader(&self.shader_path.to_string_lossy())
    }

    fn reset(&mut self, _output: &Output) -> Result<(), BackendError> {
        // Hyprland's sentinel for "no shader".
        self.hyprctl_screen_shader("[[EMPTY]]")
    }

    fn set_linear_light(&mut self, enabled: bool) -> Result<(), BackendError> {
        self.linear_light = enabled;
        Ok(())
    }

    fn supports_linear_light(&self) -> bool {
        true
    }
}

fn shader_source(saturation: Saturation, linear_light: bool) -> String {
    let template = if linear_light {
        LINEAR_SCREEN_SHADER_TEMPLATE
    } else {
        GAMMA_SCREEN_SHADER_TEMPLATE
    };
    template.replace("{SATURATION}", &format!("{:.4}", saturation.get()))
}

fn shader_path() -> Option<PathBuf> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))?;
    Some(base.join("satur8").join("hyprland-satur8.frag"))
}

fn which(bin: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|d| d.join(bin))
        .find(|p| p.is_file())
}

#[cfg(test)]
mod tests {
    use super::*;
    use satur8_core::Backend;

    fn backend() -> HyprlandBackend {
        HyprlandBackend {
            shader_path: PathBuf::from("hyprland-satur8.frag"),
            linear_light: false,
        }
    }

    #[test]
    fn gamma_shader_is_default() {
        let src = shader_source(Saturation::new(1.5), false);

        assert!(src.contains("float luma = dot(color.rgb, vec3(0.2126, 0.7152, 0.0722));"));
        assert!(src.contains("mix(vec3(luma), color.rgb, float(1.5000))"));
        assert!(!src.contains("srgb_to_linear"));
    }

    #[test]
    fn linear_shader_uses_standard_srgb_transfer_functions() {
        let src = shader_source(Saturation::new(1.5), true);

        assert!(src.contains("c <= 0.04045 ? c / 12.92"));
        assert!(src.contains("pow((c + 0.055) / 1.055, 2.4)"));
        assert!(src.contains("c <= 0.0031308 ? c * 12.92"));
        assert!(src.contains("1.055 * pow(c, 1.0 / 2.4) - 0.055"));
        assert!(src.contains("float luma = dot(linear_rgb, vec3(0.2126, 0.7152, 0.0722));"));
        assert!(src.contains("mix(vec3(luma), linear_rgb, float(1.5000))"));
        assert!(src.contains("color.a"));
    }

    #[test]
    fn set_linear_light_selects_linear_shader_for_next_apply() {
        let mut backend = backend();
        assert!(backend.supports_linear_light());
        assert!(!backend
            .shader_source(Saturation::new(1.5))
            .contains("srgb_to_linear"));

        backend.set_linear_light(true).unwrap();

        assert!(backend
            .shader_source(Saturation::new(1.5))
            .contains("srgb_to_linear"));
    }
}
