//! gamescope backend (B6) - the true last resort (PLAN.md section 5).
//!
//! gamescope is a nested compositor that runs under *any* session and applies a
//! ReShade effect to its **own** composited output - not injected into the game.
//! So `vibrance run --via gamescope -- %command%` launches the game inside
//! gamescope with our saturation shader. It needs no cooperation from the host
//! compositor, which is exactly why it is the floor nobody falls through, and
//! also why it costs an extra composite pass + a little latency. Prefer a native
//! backend everywhere one exists; this is for niche wlroots compositors (Sway,
//! minimal) that expose no color hook at all.
//!
//! Unlike the other backends this is launch-only (it wraps the game's lifetime),
//! so it is not a `Backend` impl - it's a run strategy used by `vibrance run`.

use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

use anyhow::{bail, Context, Result};
use vibrance_core::Saturation;

/// Self-contained ReShade FX. gamescope does not ship `ReShade.fxh`, so we
/// declare the backbuffer sampler and a full-screen-triangle vertex shader
/// inline. `{SATURATION}` is replaced with the baked value at install time
/// (gamescope can't set effect uniforms from the CLI, so we bake it). The math
/// is the same `mix(luma, color, s)` as every other backend.
const RESHADE_FX_TEMPLATE: &str = r#"// Generated by vibrance - do not edit; regenerated per launch.
uniform float Saturation = {SATURATION};

texture ColorTex : COLOR;
sampler Back { Texture = ColorTex; };

void VS_Tri(in uint id : SV_VertexID, out float4 pos : SV_Position, out float2 uv : TEXCOORD)
{
    uv  = float2((id << 1) & 2, id & 2);
    pos = float4(uv * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);
}

float4 PS_Vibrance(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
    float3 c = tex2D(Back, uv).rgb;
    float luma = dot(c, float3(0.2126, 0.7152, 0.0722));
    return float4(lerp(luma.xxx, c, Saturation), 1.0);
}

technique Vibrance
{
    pass { VertexShader = VS_Tri; PixelShader = PS_Vibrance; }
}
"#;

const EFFECT_NAME: &str = "Vibrance.fx";

/// Is gamescope available to wrap a launch?
pub fn is_available() -> bool {
    which("gamescope").is_some()
}

/// gamescope's per-user ReShade shader dir.
fn shader_dir() -> Result<PathBuf> {
    let base = if let Ok(x) = std::env::var("XDG_DATA_HOME") {
        if x.is_empty() {
            PathBuf::from(std::env::var("HOME").context("HOME unset")?).join(".local/share")
        } else {
            PathBuf::from(x)
        }
    } else {
        PathBuf::from(std::env::var("HOME").context("HOME unset")?).join(".local/share")
    };
    Ok(base.join("gamescope/reshade/Shaders"))
}

/// Write the saturation-baked ReShade effect and return its file name (which is
/// what `--reshade-effect` expects).
pub fn install_effect(saturation: Saturation) -> Result<String> {
    let dir = shader_dir()?;
    std::fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    let fx = RESHADE_FX_TEMPLATE.replace("{SATURATION}", &format!("{:.4}", saturation.get()));
    let path = dir.join(EFFECT_NAME);
    let mut f = std::fs::File::create(&path).with_context(|| format!("writing {}", path.display()))?;
    f.write_all(fx.as_bytes())?;
    Ok(EFFECT_NAME.to_string())
}

/// Launch `command` inside gamescope with the vibrance effect applied to
/// gamescope's output. `extra_args` are passed to gamescope before `--`
/// (e.g. `-W 2560 -H 1440 -r 240`). Returns the game's exit code. gamescope
/// exits with the game, so there's nothing to restore afterward.
pub fn run(saturation: Saturation, extra_args: &[String], command: &[String]) -> Result<i32> {
    if command.is_empty() {
        bail!("gamescope: no command to run");
    }
    if !is_available() {
        bail!("gamescope is not installed (it's the fallback backend; install it or use a native one)");
    }
    let effect = install_effect(saturation)?;

    let mut cmd = Command::new("gamescope");
    cmd.args(extra_args);
    cmd.arg("--reshade-effect").arg(&effect);
    cmd.arg("--");
    cmd.args(command);

    let status = cmd
        .status()
        .with_context(|| "launching gamescope (is it installed and runnable?)")?;
    Ok(status.code().unwrap_or(1))
}

/// Build the gamescope argv we would exec, for diagnostics / dry-run.
pub fn build_argv(effect: &str, extra_args: &[String], command: &[String]) -> Vec<String> {
    let mut v = vec!["gamescope".to_string()];
    v.extend(extra_args.iter().cloned());
    v.push("--reshade-effect".into());
    v.push(effect.into());
    v.push("--".into());
    v.extend(command.iter().cloned());
    v
}

fn which(bin: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|d| d.join(bin))
        .find(|p| p.is_file())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bakes_saturation_into_effect() {
        let fx = RESHADE_FX_TEMPLATE.replace("{SATURATION}", "1.6000");
        assert!(fx.contains("uniform float Saturation = 1.6000;"));
        assert!(!fx.contains("{SATURATION}"));
    }

    #[test]
    fn argv_has_effect_and_separator() {
        let argv = build_argv("Vibrance.fx", &["-W".into(), "2560".into()], &["cs2".into()]);
        assert_eq!(argv[0], "gamescope");
        assert!(argv.contains(&"--reshade-effect".to_string()));
        assert!(argv.contains(&"--".to_string()));
        assert_eq!(argv.last().unwrap(), "cs2");
    }
}
